### ISSUE TITLE
切换到某些特定卡池，查看卡池指令报错

### ISSUE THREAD

**Issue by zangxx66** [pcrbot/gacha#2]
`Traceback (most recent call last):
  File "/root/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "/root/HoshinoBot/hoshino/modules/priconne/gacha/__init__.py", line 155, in set_pool
    await gacha_info(bot, ev)
  File "/root/HoshinoBot/hoshino/modules/priconne/gacha/__init__.py", line 59, in gacha_info
    gacha = Gacha(_group_pool[gid])
  File "/root/HoshinoBot/hoshino/modules/priconne/gacha/gacha.py", line 11, in __init__
    self.load_pool(pool_name)
  File "/root/HoshinoBot/hoshino/modules/priconne/gacha/gacha.py", line 16, in load_pool
    pool = config[pool_name]
KeyError: 'FES'
`

卡池版本已是最新，如果切换卡池到fes或水黑等限定卡池，查看卡池将会报以上类似的错误

**Comment by var-mixer** [comment]
请检查下`config.py`中是否有`FES`这个卡池，一般情况下，自动更新只会修改`config.py`中`MIX`、`TW`、`JP`、`BL`四个卡池的内容而不会修改其他卡池，如果你原先卡池就没有`FES`池那么自动更新后也不会有。而我自己刚测试了下你所述的两个卡池，所有指令也是正常的。
HoshinoBot的版本不同也可能造成差异，但是实际上`gacha.py`文件已经2个月没更新了......所以我倾向去您再检查一下`config.py`文件。
