### ISSUE TITLE
无法通过聊天指令更新卡池，bot没有回复，后台显示update.py报错

### ISSUE THREAD

**Issue by homileak** [pcrbot/gacha#23]
[2021-08-01 10:41:43,384 nonebot] INFO: Self: 678124561, Message 812592660 from 704156982@[群:515112116]: '更新卡池'
/root/.cache/pypoetry/virtualenvs/pcrbot-f12N20ib-py3.9/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to ho
st 'api.redive.lolikon.icu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
[2021-08-01 10:41:44,560 hoshino] INFO: 开始对比角色数据
[2021-08-01 10:41:44,560 hoshino] INFO: 已开始更新角色1164的数据和图标
[2021-08-01 10:41:44,560 nonebot] ERROR: An exception occurred while running command ('更新卡池',):
[2021-08-01 10:41:44,560 nonebot] ERROR: module 'hoshino.modules.priconne._pcr_data' has no attribute 'chara_master'
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/pcrbot-f12N20ib-py3.9/lib/python3.9/site-packages/nonebot/command/__init__.py", line 881, in _real_run_command
    await asyncio.wait_for(future, timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/root/.cache/pypoetry/virtualenvs/pcrbot-f12N20ib-py3.9/lib/python3.9/site-packages/nonebot/command/__init__.py", line 173, in run
    await self.func(session)
  File "/root/pcrbot/HoshinoBot/hoshino/modules/priconne/gacha/update.py", line 231, in update_pool_chat
    status = await update_pool()
  File "/root/pcrbot/HoshinoBot/hoshino/modules/priconne/gacha/update.py", line 197, in update_pool
    await update_pcrdata()
  File "/root/pcrbot/HoshinoBot/hoshino/modules/priconne/gacha/update.py", line 67, in update_pcrdata
    _pcr_data.chara_master.add_chara(id, online_pcrdata[id])
AttributeError: module 'hoshino.modules.priconne._pcr_data' has no attribute 'chara_master'

**Comment by homileak** [comment]
问题已解决，是因为使用了旧版的人物数据_pcr_data.py导致
