### ISSUE TITLE
尝试抽卡时报错

### ISSUE THREAD

**Issue by Kelcoin** [pcrbot/gacha#28]
gacha和HoshinoBot均为最新版本
日志如下：
`[2022-06-28 19:06:24,675 gacha] INFO: Message -1930211332 triggered gacha_300.
[2022-06-28 19:06:24,685 gacha] ERROR: <class 'AttributeError'> occured when gacha_300 handling message -1930211332.
[2022-06-28 19:06:24,685 gacha] ERROR: 'coroutine' object has no attribute 'size'
Traceback (most recent call last):
  File "D:\Documents\HoshinoBot\hoshino\msghandler.py", line 21, in handle_message
    await service_func.func(bot, event)
  File "D:\Documents\HoshinoBot\hoshino\modules\priconne\gacha\__init__.py", line 280, in gacha_300
    res = concat_pic(pics)
  File "D:\Documents\HoshinoBot\hoshino\util\__init__.py", line 81, in concat_pic
    w, h = pics[0].size
AttributeError: 'coroutine' object has no attribute 'size'`

**Comment by Destiny4073** [comment]
这个问题应该是在5月8日更新的Hoshinobot中，增加了异步相关的代码，但是目前的gacha还是基于旧版改的，这部分的代码还没同步过来，近期有时间的话会加上的。

**Comment by var-mixer** [comment]
Fixed by @BossWangST 

https://github.com/pcrbot/gacha/pull/29
