### ISSUE TITLE
大概是找不到图标资源？

### ISSUE THREAD

**Issue by dfmjndm** [pcrbot/gacha#31]
使用抽卡功能时出现

[2022-07-21 22:52:19,899 gacha] ERROR: 'Chara' object has no attribute 'render_icon'
Traceback (most recent call last):
  File "/hobot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/hobot/hoshino/modules/priconne/gacha/__init__.py", line 235, in gacha_10
    res1 = await chara.gen_team_pic(result[:5], star_slot_verbose=False)
  File "/hobot/hoshino/modules/priconne/chara.py", line 107, in gen_team_pic
    src = chara.render_icon(size, star_slot_verbose)
AttributeError: 'Chara' object has no attribute 'render_icon'

请问这个图标是保存在哪个路径下

**Comment by dfmjndm** [comment]
已解决
