### ISSUE TITLE
挂了

### ISSUE THREAD

**Issue by Naexen** [pcrbot/gacha#5]
22:02:37 [ERROR] [CQHTTPMirai] java.io.IOException: ????????
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(Unknown Source)
        at kotlin.io.ByteStreamsKt.copyTo(IOStreams.kt:108)
        at kotlin.io.ByteStreamsKt.copyTo$default(IOStreams.kt:103)
        at net.mamoe.mirai.utils.FileCacheStrategy$TempCache.newImageCache(FileCacheStrategy.jvm.kt:139)
        at net.mamoe.mirai.utils.FileCacheStrategy$PlatformDefault.newImageCache(FileCacheStrategy.jvm.kt)
        at net.mamoe.mirai.utils.internal.DeferredReusableInput$init$3.invokeSuspend(DeferredReusableInput.jvm.kt:23)
        at net.mamoe.mirai.utils.internal.DeferredReusableInput$init$3.invoke(DeferredReusableInput.jvm.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.utils.internal.DeferredReusableInput.init(DeferredReusableInput.jvm.kt:18)
        at net.mamoe.mirai.qqandroid.contact.GroupImpl.uploadImage(GroupImpl.kt:401)
        at net.mamoe.mirai.utils.ExternalImageKt.upload(ExternalImage.kt:123)
        at net.mamoe.mirai.message.SendImageUtilsJvmKt.uploadAsImage(SendImageUtilsJvm.kt:111)
        at tech.mihoyo.mirai.util.CQMessgeParserKt$convertToMiraiMessage$$inlined$with$lambda$1.invokeSuspend(CQMessgeParser.kt:354)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

  [2020-09-01 22:11:46,334 gacha] INFO: Message 8279 triggered gacha_300 by PrefixTrigger.
[2020-09-01 22:11:46,366 gacha] ERROR: <class 'aiocqhttp.exceptions.ActionFailed'> occured when gacha_300 handling message 8279.
[2020-09-01 22:11:46,366 gacha] ERROR: <ActionFailed, retcode=103>
Traceback (most recent call last):
  File "E:\HoshinoBot\hoshino\msghandler.py", line 33, in handle_message
    await sf.func(bot, event)
  File "E:\HoshinoBot\hoshino\modules\priconne\gacha\__init__.py", line 272, in gacha_300
    await bot.send(ev, '\n'.join(msg), at_sender=True)
  File "D:\app\python384\lib\site-packages\aiocqhttp\__init__.py", line 256, in send
    return await self.send_msg(**params)
  File "D:\app\python384\lib\site-packages\aiocqhttp\__init__.py", line 223, in call_action
    return await self._api.call_action(action=action, **params)
  File "D:\app\python384\lib\site-packages\aiocqhttp\api_impl.py", line 186, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "D:\app\python384\lib\site-packages\aiocqhttp\api_impl.py", line 161, in call_action
    return _handle_api_result(
  File "D:\app\python384\lib\site-packages\aiocqhttp\api_impl.py", line 51, in _handle_api_result
    raise ActionFailed(retcode=result.get('retcode'))
aiocqhttp.exceptions.ActionFailed: <ActionFailed, retcode=103>
[2020-09-01 22:11:46,367 nonebot] INFO: Message 8279 is ignored

**Comment by var-mixer** [comment]
此错误：
```
aiocqhttp.exceptions.ActionFailed: <ActionFailed, retcode=103>
```
并非由某一特定插件引起，实际上无论您发送长消息或者是图片，发送失败时均有可能引发此错误。

比较可能的原因是腾讯的风控导致长消息、图片消息、包含特定文本的消息发送不出去，亦或是mirai核心的问题。而深究其原因应当向mirai开发组提交issue，而非本项目。
